# Generated by Django 3.2.7 on 2021-12-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarChartReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advanced_report_builder.report')),
                ('x_axis_scale', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily')], default=0, null=True)),
                ('x_axis_data', models.CharField(blank=True, max_length=200, null=True)),
                ('x_axis_date_range', models.PositiveSmallIntegerField(choices=[(29, 'Last 6 months'), (27, 'Last 3 months'), (33, 'Last 90 days'), (25, 'Last 2 month'), (31, 'Last 60 days'), (9, 'Last month'), (15, 'Last 28 days'), (13, 'Last 14 days'), (11, 'Last 7 days'), (18, 'Last week'), (2, 'Yesterday'), (1, 'Today'), (3, 'Tomorrow'), (4, 'This week'), (10, 'Next 7 days'), (12, 'Next 14 days'), (5, 'Next week'), (6, '2 weeks time'), (7, 'This month'), (14, 'Next 28 days'), (8, 'Next month'), (24, 'Next 2 months'), (30, 'Next 60 days'), (26, 'Next 3 months'), (32, 'Next 90 days'), (28, 'Next 6 months'), (16, 'This year'), (17, 'Last year'), (23, 'Last 18 months')], default=1)),
                ('x_label', models.CharField(blank=True, max_length=200, null=True)),
                ('y_axis_value', models.CharField(blank=True, max_length=200, null=True)),
                ('y_axis_value_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Count'), (2, 'Sum'), (3, 'Average')], default=1, null=True)),
                ('y_label', models.CharField(blank=True, max_length=200, null=True)),
                ('positive_bar_colour', models.CharField(default='801c70', max_length=10)),
                ('negative_bar_colour', models.CharField(default='801c70', max_length=10)),
                ('bar_chart_orientation', models.CharField(choices=[('bar', 'Vertical'), ('horizontalBar', 'Horizontal')], default='bar', max_length=200)),
                ('show_totals', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('advanced_report_builder.report',),
        ),
    ]
