# Generated by Django 3.2.7 on 2022-02-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
