# Generated by Django 3.2.7 on 2021-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0002_barchartreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barchartreport',
            old_name='y_axis_value_type',
            new_name='axis_value_type',
        ),
        migrations.AddField(
            model_name='barchartreport',
            name='fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
