# Generated by Django 3.2.7 on 2021-12-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0002_dashboard_dashboardreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.report'),
            preserve_default=False,
        ),
    ]
