# Generated by Django 3.2.7 on 2022-01-26 16:02

import advanced_report_builder.models
from django.db import migrations, models
import django.db.models.deletion
import time_stamped_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0003_singlevaluereport_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advanced_report_builder.report')),
            ],
            options={
                'abstract': False,
            },
            bases=('advanced_report_builder.report',),
        ),
        migrations.CreateModel(
            name='KanbanReportLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('instance_type', models.CharField(max_length=255, null=True)),
                ('heading_field', models.CharField(blank=True, max_length=200, null=True)),
                ('query', models.JSONField(blank=True, null=True)),
                ('kanban_report', models.ForeignKey(on_delete=advanced_report_builder.models.KanbanReport, to='advanced_report_builder.kanbanreport')),
                ('report_tags', models.ManyToManyField(blank=True, to='advanced_report_builder.ReportTag')),
                ('report_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
