# Generated by Django 3.2.7 on 2021-12-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0003_auto_20211217_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barchartreport',
            old_name='x_axis_scale',
            new_name='axis_scale',
        ),
    ]
