# Generated by Django 3.2.7 on 2021-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0003_dashboardreport_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardreport',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='report',
            name='held_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
