# Generated by Django 3.2.7 on 2021-12-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0004_rename_x_axis_scale_barchartreport_axis_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barchartreport',
            name='x_axis_data',
        ),
        migrations.RemoveField(
            model_name='barchartreport',
            name='x_axis_date_range',
        ),
        migrations.RemoveField(
            model_name='barchartreport',
            name='y_axis_value',
        ),
        migrations.AddField(
            model_name='barchartreport',
            name='date_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
