# Generated by Django 3.2.7 on 2022-01-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0004_kanbanreport_kanbanreportlane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanreportlane',
            name='instance_type',
        ),
        migrations.RemoveField(
            model_name='kanbanreportlane',
            name='report_tags',
        ),
    ]
