# Generated by Django 3.2.7 on 2022-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0004_customreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanreportlane',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='background_colour_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='heading_colour_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_end_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_start_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_type',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, 'Daily (single date)'), (2, 'Daily (within two date)'), (3, 'Weekly (single date)'), (4, 'Weekly (within two date)'), (5, 'Monthly (single date)'), (6, 'Monthly (within two date)')], default=0),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_type_date_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_type_end_date_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='multiple_type_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
