# Generated by Django 3.2.7 on 2021-12-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0005_auto_20211217_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barchartreport',
            name='negative_bar_colour',
        ),
        migrations.RemoveField(
            model_name='barchartreport',
            name='positive_bar_colour',
        ),
    ]
