# Generated by Django 3.2.7 on 2022-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0005_auto_20220126_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanreportlane',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
