# Generated by Django 3.2.7 on 2021-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0005_rename_held_slug_report_slug_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='display_options',
            field=models.PositiveIntegerField(choices=[(1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row')], default=2),
        ),
        migrations.AddField(
            model_name='dashboardreport',
            name='display_option',
            field=models.PositiveIntegerField(choices=[(0, 'None/Default'), (1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row')], default=0),
        ),
        migrations.AddField(
            model_name='dashboardreport',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
