# Generated by Django 3.2.7 on 2022-01-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0006_kanbanreportlane_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanreportlane',
            name='kanban_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.kanbanreport'),
        ),
    ]
