# Generated by Django 3.2.7 on 2021-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0006_auto_20211217_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='axis_scale',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, ''), (1, 'Year'), (2, 'Quarter'), (3, 'Month'), (4, 'Week'), (5, 'Day')], default=0, null=True),
        ),
    ]
