# Generated by Django 3.2.7 on 2022-01-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0007_alter_kanbanreportlane_kanban_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanbanreportlane',
            old_name='query',
            new_name='query_data',
        ),
    ]
