# Generated by Django 3.2.7 on 2021-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0007_alter_barchartreport_axis_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='axis_scale',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year'), (2, 'Quarter'), (3, 'Month'), (4, 'Week'), (5, 'Day')], null=True),
        ),
    ]
