# Generated by Django 3.2.7 on 2021-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0008_alter_barchartreport_axis_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='axis_value_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sum'), (1, 'Max'), (2, 'Min'), (3, 'Count'), (4, 'Avg')], default=3, null=True),
        ),
    ]
