# Generated by Django 3.2.7 on 2022-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0008_rename_query_kanbanreportlane_query_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanreportlane',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
