# Generated by Django 3.2.7 on 2021-12-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0008_tablereport_page_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='name_override',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
