# Generated by Django 3.2.7 on 2021-12-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0009_alter_barchartreport_axis_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='axis_value_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sum'), (2, 'Max'), (3, 'Min'), (4, 'Count'), (5, 'Avg')], default=4, null=True),
        ),
    ]
