# Generated by Django 3.2.7 on 2023-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0009_auto_20230428_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartreport',
            name='breakdown_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barchartreport',
            name='show_breakdown',
            field=models.BooleanField(default=False),
        ),
    ]
