# Generated by Django 3.2.7 on 2021-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0009_dashboardreport_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='slug_alias',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
