# Generated by Django 3.2.7 on 2022-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0009_kanbanreportlane_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanreportlane',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='order_by_ascending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kanbanreportlane',
            name='order_by_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
