# Generated by Django 3.2.7 on 2021-12-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0011_alter_singlevaluereport_single_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlevaluereport',
            name='numerator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
