# Generated by Django 3.2.7 on 2021-12-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0011_barchartreport_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='date_format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'dd/mm/yy'), (2, 'dd/mm/yyyy'), (3, 'mm/dd/yy'), (4, 'mm/dd/yyyy'), (5, 'dd-mm-yy'), (6, 'dd-mm-yyyy'), (7, 'mm-dd-yy'), (8, 'mm-dd-yyyy'), (9, 'MM d yyyy'), (10, 'd MM yyyy'), (11, 'M d yyyy'), (12, 'd M yyyy'), (13, 'yyyy'), (14, 'yy'), (15, 'mm yy'), (16, 'mm yyyy'), (17, 'MM yy'), (18, 'MM yyyy'), (19, 'b yy'), (20, 'b yyyy'), (21, 'mm'), (22, 'MM'), (23, 'd'), (24, 'WW'), (25, 'WW-YYYY'), (26, 'WW-YY')], null=True),
        ),
    ]
