# Generated by Django 3.2.7 on 2021-12-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0012_alter_barchartreport_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchartreport',
            name='axis_scale',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year'), (2, 'Quarter'), (3, 'Month'), (4, 'Week'), (5, 'Day')], default=1),
            preserve_default=False,
        ),
    ]
