# Generated by Django 3.2.7 on 2021-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0014_remove_barchartreport_bar_chart_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartreport',
            name='bar_chart_orientation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vertical'), (2, 'Horizontal')], default=1),
        ),
    ]
