# Generated by Django 3.2.7 on 2021-12-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0015_barchartreport_bar_chart_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartreport',
            name='stacked',
            field=models.BooleanField(default=False),
        ),
    ]
