# Generated by Django 5.0.7 on 2025-05-09 21:13

import django.db.models.deletion
import time_stamped_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0015_report_user_created_report_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advanced_report_builder.report')),
                ('height', models.PositiveSmallIntegerField(default=600)),
            ],
            options={
                'abstract': False,
            },
            bases=('advanced_report_builder.report',),
        ),
        migrations.CreateModel(
            name='CalendarReportDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('calendar_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.calendarreport')),
                ('report_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CalendarReportDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('heading_field', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date_field', models.CharField(blank=True, max_length=200, null=True)),
                ('end_date_field', models.CharField(blank=True, max_length=200, null=True)),
                ('background_colour_field', models.CharField(blank=True, max_length=200, null=True)),
                ('link_field', models.CharField(blank=True, max_length=200, null=True)),
                ('query_data', models.JSONField(blank=True, null=True)),
                ('calendar_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.calendarreport')),
                ('report_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype')),
                ('calendar_report_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.calendarreportdescription')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
