# Generated by Django 3.2.7 on 2021-12-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0016_barchartreport_stacked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barchartreport',
            name='date_format',
        ),
    ]
