# Generated by Django 5.0.7 on 2025-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0016_calendarreport_calendarreportdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreportdataset',
            name='display_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Name and Description'), (2, 'Description Only'), (3, 'Heading Only')], default=1),
        ),
        migrations.AddField(
            model_name='calendarreportdataset',
            name='end_date_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Field'), (2, 'Duration Field'), (3, 'Duration Fixed')], default=1),
        ),
        migrations.AddField(
            model_name='calendarreportdataset',
            name='end_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarreportdataset',
            name='end_duration_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
