# Generated by Django 5.0.7 on 2025-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0017_calendarreportdataset_display_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreport',
            name='view_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Month'), (2, 'Grid Week'), (3, 'List Week'), (4, 'Day'), (5, 'Year')], default=1),
        ),
    ]
