# Generated by Django 3.2.7 on 2021-12-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0017_remove_barchartreport_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartreport',
            name='show_blank_dates',
            field=models.BooleanField(default=True),
        ),
    ]
