# Generated by Django 3.2.7 on 2021-12-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0018_barchartreport_show_blank_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineChartReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advanced_report_builder.report')),
                ('axis_scale', models.PositiveSmallIntegerField(choices=[(1, 'Year'), (2, 'Quarter'), (3, 'Month'), (4, 'Week'), (5, 'Day')])),
                ('date_field', models.CharField(blank=True, max_length=200, null=True)),
                ('axis_value_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sum'), (2, 'Max'), (3, 'Min'), (4, 'Count'), (5, 'Avg')], default=4, null=True)),
                ('fields', models.TextField(blank=True, null=True)),
                ('x_label', models.CharField(blank=True, max_length=200, null=True)),
                ('y_label', models.CharField(blank=True, max_length=200, null=True)),
                ('show_totals', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('advanced_report_builder.report',),
        ),
    ]
