# Generated by Django 5.0.7 on 2025-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0018_calendarreport_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
