# Generated by Django 5.1.3 on 2025-10-30 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0019_multicellstyle_multivaluereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportcell',
            name='multi_cell_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.multicellstyle'),
        ),
    ]
