# Generated by Django 5.1.3 on 2025-10-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0020_multivaluereportcell_multi_cell_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportcell',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
    ]
