# Generated by Django 5.1.3 on 2026-01-02 16:07

import django.db.models.deletion
import time_stamped_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0021_multivalueheldquery_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='show_options',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='template_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=256)),
                ('field', models.CharField(max_length=200)),
                ('report_builder_class_name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.report')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
