# Generated by Django 3.2.7 on 2021-12-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0021_funnelchartreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='display_option',
            field=models.PositiveIntegerField(choices=[(1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row'), (4, '4 Reports per Row')], default=2),
        ),
        migrations.AlterField(
            model_name='dashboardreport',
            name='display_option',
            field=models.PositiveIntegerField(choices=[(0, 'None/Default'), (1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row'), (4, '4 Reports per Row')], default=0),
        ),
    ]
