# Generated by Django 5.1.3 on 2025-10-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0021_multivaluereportcell_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivaluereportcell',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
    ]
