# Generated by Django 5.1.3 on 2026-01-05 16:11

import django.db.models.deletion
import django_modals.model_fields.colour
import time_stamped_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0022_dashboardreport_show_options_report_template_style_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='colour',
            new_name='default_colour',
        ),
        migrations.AddField(
            model_name='singlevaluereport',
            name='font_colour',
            field=django_modals.model_fields.colour.ColourField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TargetColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('percentage', models.FloatField(blank=True, help_text='Less than or equal.', null=True)),
                ('colour', django_modals.model_fields.colour.ColourField(blank=True, max_length=10, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.target')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
