# Generated by Django 3.2.7 on 2021-12-24 12:45

from django.db import migrations, models
import time_stamped_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0022_auto_20211224_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='report_tags',
            field=models.ManyToManyField(blank=True, to='advanced_report_builder.ReportTag'),
        ),
    ]
