# Generated by Django 5.1.3 on 2025-10-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0022_alter_multivaluereportcell_report_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='multivaluereportcell',
            constraint=models.UniqueConstraint(fields=('report', 'row', 'column'), name='multi_value_report_cell_unique'),
        ),
    ]
