# Generated by Django 5.1.3 on 2025-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0023_multivaluereportcell_multi_value_report_cell_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportcell',
            name='sample_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='multivaluereportcell',
            name='multi_value_type',
            field=models.IntegerField(choices=[(0, 'Static Text'), (1, 'Count'), (2, 'Sum'), (4, 'Percent'), (5, 'Percent from Count'), (6, 'Average Sum from Count'), (7, 'Average Sum over Time'), (8, 'Average Sum over Time (Excluding Weekends)'), (9, 'Equation')], default=0),
        ),
        migrations.AlterField(
            model_name='singlevaluereport',
            name='single_value_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Count'), (2, 'Sum'), (3, 'Count & Sum'), (4, 'Percent'), (5, 'Percent from Count'), (6, 'Average Sum from Count'), (7, 'Average Sum over Time'), (8, 'Average Sum over Time (Excluding Weekends)')], default=1),
        ),
    ]
