# Generated by Django 5.1.3 on 2026-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0023_rename_colour_target_default_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='period_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Yearly')], default=3),
        ),
    ]
