# Generated by Django 5.1.3 on 2025-11-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0024_multivaluereportcell_sample_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multicellstyle',
            name='align_type',
            field=models.IntegerField(choices=[(0, 'left'), (1, 'Centre'), (2, 'Right')], default=0),
        ),
    ]
