# Generated by Django 5.1.3 on 2026-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0024_alter_target_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreport',
            name='size',
            field=models.PositiveIntegerField(choices=[(1, 'Standard'), (2, 'Large')], default=1),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='display_option',
            field=models.PositiveIntegerField(choices=[(1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row'), (4, '4 Reports per Row'), (6, '6 Reports per Row')], default=2),
        ),
        migrations.AlterField(
            model_name='dashboardreport',
            name='display_option',
            field=models.PositiveIntegerField(choices=[(0, 'None / Default'), (1, '1 Report per Row'), (2, '2 Reports per Row'), (3, '3 Reports per Row'), (4, '4 Reports per Row'), (6, '6 Reports per Row')], default=0),
        ),
    ]
