# Generated by Django 5.1.3 on 2025-11-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0025_multicellstyle_align_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivaluereportcell',
            name='multi_cell_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advanced_report_builder.multicellstyle'),
        ),
    ]
