# Generated by Django 5.1.3 on 2026-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0025_dashboardreport_size_alter_dashboard_display_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='period_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Period'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Yearly')], default=3),
        ),
    ]
