# Generated by Django 5.1.3 on 2025-11-19 11:00

import django.db.models.deletion
import time_stamped_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0026_alter_multivaluereportcell_multi_cell_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiValueReportColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('column', models.PositiveSmallIntegerField()),
                ('width_type', models.PositiveSmallIntegerField(choices=[(0, '%'), (1, 'Pixels')], default=0)),
                ('width', models.PositiveSmallIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.report')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
