# Generated by Django 5.1.3 on 2025-11-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0027_multivaluereportcolumn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multivaluereportcell',
            old_name='extra_query',
            new_name='extra_query_data',
        ),
        migrations.RenameField(
            model_name='multivaluereportcell',
            old_name='query',
            new_name='query_data',
        ),
    ]
