# Generated by Django 5.1.3 on 2025-11-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0028_rename_extra_query_multivaluereportcell_extra_query_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multivaluereportcell',
            old_name='sample_text',
            new_name='label',
        ),
    ]
