# Generated by Django 5.2.9 on 2026-07-02 15:17

import django.db.models.deletion
import time_stamped_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0030_tablereport_allow_new_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportcell',
            name='group_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MultiValueReportRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('row', models.PositiveSmallIntegerField()),
                ('group_field', models.CharField(blank=True, max_length=200, null=True)),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Year'), (2, 'Quarter'), (3, 'Month'), (4, 'Week'), (5, 'Day')], default=4)),
                ('base_query', models.JSONField(blank=True, null=True)),
                ('label_format', models.CharField(default='%d/%m/%Y', max_length=32)),
                ('limit', models.PositiveSmallIntegerField(default=60)),
                ('descending', models.BooleanField(default=False)),
                ('show_blank_dates', models.BooleanField(default=False)),
                ('multi_value_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_report_builder.multivaluereport')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('multi_value_report', 'row'), name='multi_value_report_row_unique')],
            },
        ),
    ]
