# Generated by Django 5.2.9 on 2026-09-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0031_multivaluereportcell_group_field_multivaluereportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendarreportdataset',
            name='report_type',
            field=models.ForeignKey(limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='calendarreportdescription',
            name='report_type',
            field=models.ForeignKey(limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='kanbanreportdescription',
            name='report_type',
            field=models.ForeignKey(limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='kanbanreportlane',
            name='report_type',
            field=models.ForeignKey(limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='multivalueheldquery',
            name='report_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='multivaluereportcell',
            name='report_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='multivaluereportrow',
            name='report_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to='advanced_report_builder.reporttype'),
        ),
    ]
