# Generated by Django 5.2.9 on 2026-07-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0032_remove_multivaluereport_dynamic_row_base_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportcell',
            name='period_date_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
