# Generated by Django 5.2.9 on 2026-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0033_multivaluereportcell_period_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivaluereportrow',
            name='show_blank_dates',
            field=models.BooleanField(default=False),
        ),
    ]
