exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "site-packages",
    "venv",
    "migrations",
]

line-length = 120
indent-width = 4
target-version = "py312"

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"

[lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I"
]
exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "site-packages",
    "venv",
    "migrations",
    "apps.py"
]

