# Generated by Django 3.2.7 on 2021-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
