# Generated by Django 3.2.7 on 2022-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
