# Generated by Django 3.2.7 on 2022-01-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='companyinformation', serialize=False, to='report_builder_examples.company')),
                ('value', models.IntegerField()),
                ('incorporated_date', models.DateField()),
            ],
        ),
    ]
