# Generated by Django 3.2.7 on 2022-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0002_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background_colour',
            field=models.CharField(default='90EE90', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='text_colour',
            field=models.CharField(default='454B1B', max_length=8),
        ),
    ]
