# Generated by Django 3.2.7 on 2021-10-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0002_report_instance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportreporttype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reporttablereport',
            name='report_ptr',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportReportType',
        ),
        migrations.DeleteModel(
            name='ReportTableReport',
        ),
    ]
