# Generated by Django 3.2.7 on 2021-10-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_auto_20211012_1308'),
        ('report_builder_examples', '0003_auto_20211005_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReportFields',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report_builder.report')),
                ('notes', models.TextField()),
            ],
        ),
    ]
