# Generated by Django 3.2.7 on 2022-03-17 09:23

from django.db import migrations, models
import django.db.models.deletion
import time_stamped_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_report_builder', '0006_auto_20220310_1147'),
        ('report_builder_examples', '0004_company_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('created', time_stamped_model.models.CreationDateTimeField(auto_now_add=True)),
                ('modified', time_stamped_model.models.ModificationDateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='advanced_report_builder.report')),
                ('requires_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ExtraReportFields',
        ),
    ]
