# Generated by Django 3.2.7 on 2021-11-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0007_auto_20211116_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
