# Generated by Django 5.0.7 on 2025-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0010_userprofile_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='temperature',
            field=models.IntegerField(choices=[(0, 'Cold'), (1, 'Warm'), (2, 'Hot')], default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
