# Generated by Django 5.0.7 on 2025-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0011_contract_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='temperature',
            field=models.IntegerField(choices=[(0, 'Cold'), (1, 'Warm'), (2, 'Hot')], default=0),
        ),
    ]
