# Generated by Django 5.0.7 on 2025-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0012_tallygroup_tally_tally_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tally',
            name='tally_tags',
            field=models.ManyToManyField(blank=True, to='report_builder_examples.tallytag'),
        ),
    ]
