# Generated by Django 5.0.7 on 2025-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0014_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycategory',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='reportpermission',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'get_latest_by': 'created'},
        ),
    ]
