# Generated by Django 5.1.3 on 2025-10-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0015_alter_companycategory_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
