# Generated by Django 5.1.3 on 2026-01-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder_examples', '0016_person_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='description',
            field=models.CharField(blank=True, max_length=1025, null=True),
        ),
    ]
