# Generated by Django 3.2.7 on 2021-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0003_auto_20211117_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportquery',
            name='query',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
