OUTPUT_TYPE_GANTT = 0
OUTPUT_TYPE_CALENDAR = 1
OUTPUT_TYPE_SORTABLE_TABLE = 2
OUTPUT_TYPE_TABLE = 3
OUTPUT_TYPE_BAR_CHART = 4
OUTPUT_TYPE_SINGLE_VALUE = 5
OUTPUT_TYPE_CUSTOM = 6
OUTPUT_TYPE_LINE_CHART = 7
OUTPUT_TYPE_FUNNEL = 8

